# Site settings
title: Stanley Shi @ Shanghai
email: deming.shi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Personal blog for Stanley Shi
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stanley-shi.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  stanley-shi

# Build settings
markdown: kramdown

highlighter: pygments
github:

paginate: 15

collections:
  life:
    output: true
